### ISSUE TITLE
Icon has not appeared

### ISSUE THREAD

**Issue by dot-clear** [adarsh-sgh/homenote#7]
I installed the Home Note plugin a few weeks ago and it was working well.
Now the Home Note icon has not appeared in a new Joplin installation. It's trying to open an old note.

## Environment

Joplin version: 2.5.12 portable
Platform: Windows
OS specifics: Win10

<details>
 <summary>Console Logs</summary>

```
18:29:13: joplin.plugins: Uncaught exception in plugin "com.lki.homenote": Error: No such note: 2d1b2e9365f04b609b810c225d694fe3	C:\Users\Username\AppData…n\lib\Logger.js:188 
    at C:\Users\Username\AppData…ands\openNote.js:23
    at Generator.next (<anonymous>)
    at fulfilled (C:\Users\Username\AppData…mands\openNote.js:5)
    at processTicksAndRejections (internal/process/task_queues.js:95)
log	@	C:\Users\Username\AppData…n\lib\Logger.js:188
error	@	C:\Users\Username\AppData…in\lib\Logger.js:64
(anonymous)	@	C:\Users\Username\AppData…JoplinPlugins.js:47
Promise.catch (async)		
(anonymous)	@	C:\Users\Username\AppData…JoplinPlugins.js:41
(anonymous)	@	C:\Users\Username\AppData…\JoplinPlugins.js:8
__awaiter	@	C:\Users\Username\AppData…\JoplinPlugins.js:4
register	@	C:\Users\Username\AppData…JoplinPlugins.js:34
(anonymous)	@	C:\Users\Username\AppData…teSandboxCall.js:50
(anonymous)	@	C:\Users\Username\AppData…uteSandboxCall.js:8
__awaiter	@	C:\Users\Username\AppData…uteSandboxCall.js:4
executeSandboxCall	@	C:\Users\Username\AppData…teSandboxCall.js:37
(anonymous)	@	C:\Users\Username\AppData…PluginRunner.js:137
(anonymous)	@	C:\Users\Username\AppData…s\PluginRunner.js:8
__awaiter	@	C:\Users\Username\AppData…s\PluginRunner.js:4
(anonymous)	@	C:\Users\Username\AppData…PluginRunner.js:110
emit	@	events.js:376
emit	@	domain.js:470
onMessage	@	electron/js2c/renderer_init.js:81
```

**Comment by adarsh-sgh** [comment]
Thanks for detailed Bug-report @dot-clear 
probably problem was because this bug fix was still not published https://github.com/adarsh-sgh/homenote/commit/f5a77cdec5568a63852d971e6215561e8f58602b
Try updating the plugin and it should work fine

# Steps To Update Plugin
1. Open Joplin
2. Press <kbd>Ctrl</kbd><kbd>,</kbd> 
3. Select Plugins from left pane
4. Click on update button and then restart joplin
![image](https://user-images.githubusercontent.com/63918341/142013710-736260f8-14b4-48b1-85e5-53bbb9967aa2.png)
 Let me know if it worked so that we can close the issue or work on it if it still exists

**Comment by dot-clear** [comment]
I already have the v1.0.2 plugin from [here](https://github.com/joplin/plugins/blob/master/README.md#plugins).

**Comment by dot-clear** [comment]
With the v1.0.3, the Home Note plugin work again ! Thank you.
